services:

  bl01t-di-cam-01:

    extends:
      service: linux_ioc
      file: ../../include/ioc.yml

    image: ghcr.io/epics-containers/ioc-adsimdetector-runtime:2024.7.2b2

    labels:
      version: 0.1.0

    environment:
      IOCSH_PS1: bl01t-di-cam-01 >
      IOC_NAME: bl01t-di-cam-01
      IOC_PREFIX: BL01T-DI-CAM-01

    volumes:
      - ../../opi/iocs/bl01t-di-cam-01:/epics/opi

    command: /epics/ioc/start.sh

    configs:
      - source: bl01t-di-cam-01_config
        target: epics/ioc/config

configs:
  bl01t-di-cam-01_config:
    file: ./config

include:
  - path:
    - include/networks.yml
