# When deploying IOCs to a server with docker, the choice is:
#
# 1. Use host network so their PVs available on the subnet
# 2. Run a ca-gateway on each server and add all servers to client's
#    EPICS_CA_ADDR_LIST
#
# at present the only available option for podman is to use host network

services:

  # ca-gateway for development #################################################

  ca-gateway-develop: &ca-gateway

    image: ghcr.io/epics-containers/docker-ca-gateway:2.1.3ec1

    expose:
      - 5064-5065/udp
      - 5064-5065

    ports:
      # bind to localhost to isolate channel access to this host only
      - 127.0.0.1:5064:5064/udp
      - 127.0.0.1:5064-5065:5064-5065

    restart: unless-stopped

    networks:
      channel_access:
        ipv4_address: 172.20.255.254

    configs:
      - source: ca-gateway_config
        target: /config

    command: -cip 172.20.255.255 -pvlist /config/pvlist -access /config/access -log /dev/stdout -debug 1

    profiles:
      - develop

  # per server ca-gateway for deployment #######################################
  ca-gateway-deploy:

    <<: *ca-gateway

    ports:
    # TODO - drop the IP address but also set up pvlist to make sure there
    # are no loops - I need to look into safe config for per server ca-gateways
    - 127.0.0.1:5064:5064/udp
    - 127.0.0.1:5064-5065:5064-5065

    command: -cip 172.20.255.255 -pvlist /config/pvlist -access /config/access -log /dev/stdout -debug 1

    profiles:
      - deploy

configs:
  ca-gateway_config:
    file: ./config
